### ISSUE TITLE
No Ninja build files

### ISSUE THREAD

**Issue by udif** [PacktPublishing/Learn-LLVM-9#26]
On page 8, (PDF page 27), the recommended way to get a Ninja build is to use:
```
cmake –G Ninja -DLLVM_ENABLE_PROJECTS=clang ../llvm
```
But on my system (Ubuntu 22.04) with the default cmake (3.22.1), no build.ninja file is generated. Checking CMakeCache.txt reveals that  a simple Unix Makefile Generator is used instead of the Ninja Generator.
What I found out is that the `cmake` arguments order needs to be changed:
```
cmake -DLLVM_ENABLE_PROJECTS=clang -G Ninja ../llvm
```

**Comment by packt-irfaa** [comment]
The issue can be solved in 2 different ways: 

1. Add option -G Ninja to the command line
2. Or before running CMake, set the CMAKE_GENERATOR environment variable
        - On Windows: set CMAKE_GENERATOR=Ninja
        - On Linux/bash: export CMAKE_GENERATOR=Ninja
